package tc.oc.pgm.entity;

public enum MobAnimation {
  SWING_MAIN_HAND,
  SWING_OFFHAND,
  ALLAY_START_DANCING,
  ALLAY_STOP_DANCING,
  SHEEP_EAT_GRASS,
  IRON_GOLEM_ROSE,
  IRON_GOLEM_SHEATH,
  WOLF_SHAKE,
  WOLF_SHAKE_STOP,
  RAVAGER_STUNNED,
  RAVAGER_ROARED,
  WARDEN_TENDRIL_SHAKE,
  WARDEN_SONIC_ATTACK,
  GOAT_LOWER_HEAD,
  GOAT_RAISE_HEAD
}
